### ISSUE TITLE
Problem with pyro compiling individually listed scripts?

### ISSUE THREAD

**Issue by rjstone** [joelday/papyrus-lang#100]
Filed as https://github.com/fireundubh/pyro/issues/3

**Describe the bug**
JonathanOstrusToday at 2:36 AM:

```
(VSCode papyrus-lang fork 1.3.3vsc.77)
[CMPL] Compiling "TestScript"...
[WARN] No source scripts were indexed. Possible reason: No source scripts were recently modified.
Traceback (most recent call last):
  File "c:\Users\Dream Machine\.vscode\extensions\joelday.papyrus-lang-vscode-2.19.1\pyro\pyro_cli\__main__.py", line 145, in <module>
  File "c:\Users\Dream Machine\.vscode\extensions\joelday.papyrus-lang-vscode-2.19.1\pyro\pyro_cli\__main__.py", line 81, in run
ValueError: not enough values to unpack (expected 2, got 0)
The terminal process terminated with exit code: 1
```
It actually compiled the file tho
this is the ppj 
```
<?xml version='1.0'?><!-- Game is either sse, tesv, or fo4 -->
<PapyrusProject xmlns="PapyrusProject.xsd" 
    Flags="TESV_Papyrus_Flags.flg" 
    Game="sse" 
    Output="Scripts" 
    Optimize="false" 
    Release="false" 
    Final="false">
    <Imports>
        <Import>.\Source\Scripts</Import>
        <Import>I:\Games\Steam Library\steamapps\common\Skyrim Special Edition\Data\Source\Scripts</Import>
    </Imports>
<Scripts>
<Script>TestScript</Script>
</Scripts>
</PapyrusProject>
```
**To Reproduce**
See previous.

**Comment by jbostrus** [comment]
After further testing I found the error occurs when using <Scripts> section instead of <Folders> for the source input.

**Comment by rjstone** [comment]
This should be fixed in the latest pyro in the extension
