### ISSUE TITLE
Int32 Error Handling

### ISSUE THREAD

**Issue by Deadmano** [joelday/papyrus-lang#40]
When working with numbers as part of my test case suite, I get the following error:

```
[Skyrim]: Value was either too large or too small for an Int32.
(System.OverflowException: Value was either too large or too small for an Int32.
   at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
   at System.Int32.Parse(String s)
   at DarkId.Papyrus.LanguageService.Program.Syntax.NodeBinder.<>c__DisplayClass35_1.<BindLiteralExpression>b__1(IntLiteralNode literalNode, Scanner`1 _) in C:\projects\papyrus-lang\src\DarkId.Papyrus.LanguageService\Program\Syntax\NodeBinder.cs:line 699
   at DarkId.Papyrus.LanguageService.Program.Syntax.NodeBinder.CreateNode[T](SyntaxNode parent, Scanner`1 parentChildren, Action`2 bindAction) in C:\projects\papyrus-lang\src\DarkId.Papyrus.LanguageService\Program\Syntax\NodeBinder.cs:line 898)
```

The numbers in question `-2500483647` and `6985425358` which should never exist, but just for case-tests they do, to check for proper behaviour.

**Comment by minkir014** [comment]
This message is sent by skyrim so I don't think the problem in extension.
Value was either too large or too small for an Int32.

**Comment by Scrivener07** [comment]
With at least [v2.12.1](https://github.com/joelday/papyrus-lang/releases/tag/v2.12.1)
the message is way more user friendly now. I tried with the sample papyrus below and got a nice warning.

```papyrus
Scriptname Example
int low = -2500483647
int high = 6985425358
```
```
[Creation Kit]: "2500483647" is out of bounds for an integerPapyrus(0)
[Creation Kit]: "6985425358" is out of bounds for an integerPapyrus(0)
```
#### Notes
* Notice the *sign* is missing from the value warning. 
* Also looks like a typo. Missing space character and a period to end the sentence. Error is reported on the `Scriptname` element @ (0).
